name: healthcheck
version: git
summary: The health-check command-line tool concurrently checks all target groups' health status.
description: |
  The health-check command-line tool concurrently checks all target groups' health status (for target groups that are attached to a load balancer).
  The program returns 0 when you have at least one healthy target for each service.
architectures:
  - build-on: arm64
assumes: [snapd2.45]
base: core18
 
grade: stable
confinement: strict
 
apps:
  tfswihealthchecktch:
    command: bin/healthcheck
    plugs:
      - home
      - network
      - network-bind
      
parts:
  healthcheck:
    source: .
    plugin: go
    go-importpath: github.com/warrensbox/health-check
    build-packages:
      - gcc-multilib
    go-buildtags:
      - healthcheck
    override-build: 
      go build  -o ../install/bin/healthcheck