# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/warrensbox/health-checker

    steps:
      - checkout
      - run: 
          command: |    
            set +e  
            echo "Building website" 
            # sudo apt-get install python3
            # sudo apt-get install python3-pip
            # pip3 install mkdocs-material
            # cd www
            # mkdocs gh-deploy --force
            # cd ..

            echo "Building application" 
            go get -v -t -d ./...
            go vet -tests=false ./...
            go test -v ./...
            mkdir -p build
            go build -v -o build/health-check